name: Generate Snake

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Generate Snake Animation
        run: |
          python generate_snake.py
          ls -al  # Check if snake.svg exists

      - name: Create Output Directory
        run: mkdir -p output/dist

      - name: Move Snake.svg
        run: mv snake.svg output/dist/snake.svg

      - name: Push Changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add output/dist/snake.svg
          git commit -m "Generate snake animation"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
